name: LeetCode Cron Bot

on:
  schedule:
    - cron: "30 16 * * *" # Runs at 16:30 UTC (which is 10:00 PM IST)

  workflow_dispatch:


jobs:

  run-bot:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22


      - name: Install dependencies
        run: npm install


      - name: Run bot
        env:
          CSRFTOKEN: ${{ secrets.CSRFTOKEN }}
          COOKIE: ${{ secrets.COOKIE }}
          SMTP_USER:${{ secrets.SMTP_USER }}
          SMTP_PASS:${{ secrets.SMTP_PASS}}

        run: node server.js